In [3]:
import numpy as np
import pandas as pd

In [2]:
# How likely is it that you roll doubles when rolling two dice?

In [93]:
n_trials = nrows = 10**4
n_dice = ncols = 2

In [94]:
roll = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows,ncols)
roll

array([[5, 5],
       [2, 6],
       [2, 1],
       ...,
       [1, 3],
       [6, 1],
       [1, 5]])

In [95]:
rolls = pd.DataFrame(roll)

In [96]:
rolls.apply(lambda row : True if row.values[0] == row.values[1] else False, axis = 1).mean()

0.1699

In [7]:
#2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of 
#getting more than 3 heads?

In [8]:
n_trials = 8
n_reps = 10_000

In [9]:
flips = np.random.choice([0, 1], n_trials * n_reps).reshape(n_reps,n_trials)
flips.shape

(10000, 8)

In [10]:
prob_three_heads = pd.DataFrame(flips)



In [17]:
prob_three_heads.apply(lambda row : True if row.sum() == 3 else False, axis = 1).mean() #exactly 3 heads

0.221

In [12]:
prob_three_heads.apply(lambda row : True if row.sum() > 3 else False, axis = 1).mean() #greater than 3 heads

0.6395

In [14]:
prob_three_heads.apply(lambda row : True if row.sum() <= 3 else False, axis = 1).mean() #less than or equal to 3 heads

0.3605

In [ ]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that 
# Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past 
# both have data science students on them?

In [ ]:
ratio_ds_to_wd = 1/4 #unfair coin toss

In [18]:
n_trials = 2
n_reps = 1_000

In [35]:
ds = np.random.choice([0,0,0,1], n_trials * n_reps).reshape(n_reps, n_trials)
ds

0.2495

In [33]:
prob_two_ds = pd.DataFrame(ds)

In [98]:
prob_two_ds.apply(lambda row : True if row.sum() == 2 else False, axis = 1).mean()

0.063

In [ ]:
# Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able 
# to buy some poptarts on Friday afternoon?

In [47]:
n_trials = 5 #cumulative probability
n_reps = 10_000

In [70]:
pt_consume_rounded = np.round(np.random.normal(3, 1.5, n_trials * n_reps ),0).reshape(n_reps, n_trials).astype('int64')
pt_consume

array([[2, 2, 2, 1, 3],
       [3, 3, 4, 1, 5],
       [2, 4, 2, 2, 5],
       ...,
       [4, 2, 7, 4, 2],
       [3, 3, 3, 2, 4],
       [0, 9, 5, 4, 3]])

In [63]:
np.where(pt_consume_rounded < 0, 0, pt_consume_rounded) #if less than 0,then 0; if more, use the original number

In [71]:
prob_pt_friday = pd.DataFrame(pt_consume_rounded)

In [100]:
prob_pt_friday.apply(lambda row : True if row.sum() < 17 else False, axis = 1).mean()


0.6656

In [ ]:
#5. Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# If a man and woman are chosen at random, P(woman taller than man)?

In [78]:
n_reps = 10_000

In [87]:
ht_male = 178
st_male = 8
ht_female = 170
st_female = 6

In [89]:
(np.random.normal(ht_female, st_female, n_reps) > np.random.normal(ht_male, st_male, n_reps)).mean()

0.2158

In [90]:
#6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
# installation issue? 100 students?

# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

# How likely is it that 450 students all download anaconda without an issue?

In [91]:
prob_failure = 1/250
prob_failure

0.004

In [133]:
columns = 1
n_reps1 = 50
n_reps2 = 100
n_reps3 = 150
n_reps4 = 450
n_reps5 = 100_000

In [156]:
x = np.random.choice([0,1],n_reps4 * columns, p = [249/250, 1/250]).reshape(n_reps4, columns)

In [157]:
x

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [158]:
x.sum()/len(x)

0.0022222222222222222

In [ ]:
#There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you 
# haven't seen a food truck there in 3 days. How unlikely is this?

In [1]:
n = 10_000
p_food_truck = .7
p_no_food_truck = 1 - p_food_truck

In [4]:
lunches = np.random.choice(['Food Truck', 'No Food Truck'], (n, 3), p=[p_food_truck, p_no_food_truck])
lunches

array([['Food Truck', 'No Food Truck', 'Food Truck'],
       ['No Food Truck', 'Food Truck', 'Food Truck'],
       ['No Food Truck', 'Food Truck', 'No Food Truck'],
       ...,
       ['No Food Truck', 'Food Truck', 'No Food Truck'],
       ['Food Truck', 'No Food Truck', 'Food Truck'],
       ['No Food Truck', 'Food Truck', 'Food Truck']], dtype='<U13')

In [5]:
lunches == 'No Food Truck'

array([[False,  True, False],
       [ True, False, False],
       [ True, False,  True],
       ...,
       [ True, False,  True],
       [False,  True, False],
       [ True, False, False]])

In [6]:
(lunches == 'No Food Truck').all(axis=1).mean()

0.0291

In [7]:
lunches = np.random.choice(['Food Truck', 'No Food Truck'], (n, 5), p=[p_food_truck, p_no_food_truck])
lunches

array([['No Food Truck', 'Food Truck', 'Food Truck', 'Food Truck',
        'No Food Truck'],
       ['No Food Truck', 'Food Truck', 'No Food Truck', 'Food Truck',
        'Food Truck'],
       ['Food Truck', 'No Food Truck', 'Food Truck', 'No Food Truck',
        'No Food Truck'],
       ...,
       ['Food Truck', 'Food Truck', 'Food Truck', 'Food Truck',
        'No Food Truck'],
       ['Food Truck', 'Food Truck', 'Food Truck', 'No Food Truck',
        'Food Truck'],
       ['Food Truck', 'No Food Truck', 'No Food Truck', 'Food Truck',
        'Food Truck']], dtype='<U13')

In [8]:
(lunches == 'Food Truck').any(axis=1).mean()

0.9981

In [ ]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [9]:
row = np.random.choice(range(365),23)
row

array([261, 186,   2, 148, 156,   1,  47,  41,   1,  31, 182, 277, 221,
       327, 153, 244,  23, 148, 345, 330, 271, 138, 359])

In [10]:
np.unique(np.array([1,2,3,2,2,1,1,2]))

array([1, 2, 3])

In [11]:
np.random.choice(range(365),23)
np.unique(row).size < 23

True

In [13]:
n_sims = 10_000
n_people = 23

In [14]:
birthdays = np.random.choice(range(365), (n_sims, n_people))
birthdays

array([[123, 246, 135, ..., 327, 182, 109],
       [192, 225, 123, ..., 342, 317, 164],
       [209,  12,  72, ...,  58, 312,  30],
       ...,
       [202, 148,  22, ...,  88, 219, 325],
       [ 99,  65, 185, ..., 217, 200,  64],
       [ 85,  39, 230, ...,  40, 351, 161]])

In [15]:
[np.unique(row).size for row in birthdays]

[23,
 22,
 23,
 23,
 23,
 23,
 23,
 23,
 22,
 21,
 22,
 23,
 22,
 22,
 22,
 22,
 22,
 23,
 20,
 21,
 23,
 23,
 23,
 21,
 19,
 22,
 23,
 23,
 21,
 23,
 22,
 23,
 23,
 21,
 23,
 23,
 22,
 21,
 22,
 23,
 22,
 23,
 22,
 23,
 22,
 21,
 23,
 22,
 23,
 22,
 23,
 22,
 23,
 21,
 23,
 23,
 21,
 22,
 21,
 23,
 23,
 22,
 23,
 23,
 23,
 22,
 22,
 21,
 22,
 22,
 22,
 22,
 21,
 22,
 22,
 23,
 20,
 23,
 23,
 22,
 23,
 21,
 22,
 23,
 22,
 22,
 22,
 22,
 23,
 22,
 23,
 22,
 21,
 21,
 22,
 22,
 23,
 23,
 23,
 23,
 22,
 22,
 22,
 22,
 22,
 22,
 23,
 22,
 21,
 22,
 23,
 18,
 22,
 23,
 22,
 23,
 23,
 23,
 22,
 23,
 23,
 22,
 23,
 22,
 23,
 21,
 22,
 22,
 23,
 23,
 23,
 22,
 23,
 23,
 23,
 22,
 23,
 23,
 23,
 23,
 20,
 21,
 22,
 23,
 22,
 23,
 21,
 21,
 21,
 22,
 21,
 22,
 22,
 22,
 22,
 23,
 22,
 23,
 23,
 23,
 21,
 23,
 22,
 19,
 21,
 21,
 22,
 23,
 21,
 23,
 22,
 21,
 23,
 22,
 22,
 21,
 23,
 23,
 22,
 22,
 23,
 23,
 21,
 22,
 21,
 21,
 22,
 22,
 22,
 21,
 22,
 23,
 22,
 20,
 23,
 23,
 22,
 23,
 23,
 22,


In [16]:
n_sims = 10_000
n_people = 29

birthdays = np.random.choice(range(365), (n_sims, n_people))

n_unique_birthdays = np.array([np.unique(row).size for row in birthdays])

(n_unique_birthdays < n_people).mean()

0.6862

In [17]:
s = pd.DataFrame(birthdays).iloc[0, :]
s

0     309
1     236
2      35
3      90
4     208
5      86
6     282
7     363
8     199
9      90
10     83
11     99
12    348
13    271
14     36
15    173
16     19
17    248
18     30
19     50
20    229
21    324
22    238
23    236
24     46
25      5
26    150
27    313
28    253
Name: 0, dtype: int64

In [18]:
s.nunique

<bound method IndexOpsMixin.nunique of 0     309
1     236
2      35
3      90
4     208
5      86
6     282
7     363
8     199
9      90
10     83
11     99
12    348
13    271
14     36
15    173
16     19
17    248
18     30
19     50
20    229
21    324
22    238
23    236
24     46
25      5
26    150
27    313
28    253
Name: 0, dtype: int64>

In [19]:
(pd.DataFrame(birthdays).apply(lambda s: s.nunique(), axis=1) < 29).mean()

0.6862

In [20]:
(pd.DataFrame(birthdays).nunique(axis=1) < 29).mean()

0.6862